name: CI - Build & Push to Public ECR

on:
  push:
    branches:
      - main

env:
  MODULE_NAME: hcl-appointment-service
  ECR_PUBLIC_URI: public.ecr.aws/m7n8t2b8/hcl-appointment-service
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: 'SubbuHCL/appointment-service'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon Public ECR
        run: |
          aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and Push Docker Image to Public ECR
        run: |
          docker build -t $MODULE_NAME .
          docker tag $MODULE_NAME $ECR_PUBLIC_URI:${{ github.sha }}
          docker push $ECR_PUBLIC_URI:${{ github.sha }}
